### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by StanGirard** [padok-team/terraform-azurerm-network#4]
- [ ]  It works in production
- [x]  It allows data backup (if needed)
- [x]  It allows rotation of secrets
- [x]  It allows to store secrets in Key Vault
- [x]  It encrypts data by default with Azure key or with user provided keys
- [x]  It allows outputing of logs in other solutions
- [x]  It allows replication and high availability
- [x]  It allows integration in VNET (Needs to figure out how to manager private endpoint)
- [x]  It allows control on network flows
